### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by bagl0025** [mmozeiko/RcloneBrowser#132]
I have a computer shared by many users that use rclone to upload data to various google drives. Currently all configured remotes are accessible by everyone, they stay logged in. Is it possible to automatically log them out so that each time someone tries to access a remote it requires them to login again?

Thanks!

**Comment by mmozeiko** [comment]
Not sure what you mean by "login". GUI does not login anywhere. What you should do is to use encrypted rclone config file. Then GUI will ask password when it will need to use rclone. But for it to work securely you really should use different users on same computer to isolate environment. Otherwise no "log out" feature will help you, because somebody will simply install keylogger in background and will get rclone password.

So this is really out of the scope of GUI.
