### ISSUE TITLE
Make rename action run in Jobs

### ISSUE THREAD

**Issue by Rhilip** [mmozeiko/RcloneBrowser#135]
Now, with Rclone Browser 1.2
When I want to rename the file or dir, the rename action will lock the main process and I can't do anything until the rename action finish.
It seems unnessary and waste time.
Can you let the rename action run as job ,so that I can quickly rename file one and another?

**Comment by mmozeiko** [comment]
I suggest to use "rclone mount" for this kind of functionality instead.
Properly implementing asynchronous features in GUI is major effort. Because changes in GUI will need to reflect result which can happen later - and if you do multiple actions at the same time, then the result might differ whether first finishes first, or second one finishes first.
