### ISSUE TITLE
Sync options?

### ISSUE THREAD

**Issue by klouny** [mmozeiko/RcloneBrowser#15]
Hi, this isn't so much an issue as a question. I'm a tad confused about the "sync" option. All the options say "delete before/after/during transfer", does that mean that it's going to delete the source file? What I would like is to do a full backup using "copy," then periodically use "sync" to upload any changed/added files then have rclone delete the old files from the destination, NOT the source. Is this possible?

**Comment by mmozeiko** [comment]
Sync means it will make destination look exactly as source. This means if source has files A and B, and destination has files B and C, then after sync source and destination will have files A and B. A file will be copied from source to destination. and C file will be deleted from destination. Source won't change.

**Comment by klouny** [comment]
Great, fantastic. Does it compare the files as well to replace? So let's say source folder has files A and B and destination folder also has A and B but A source has been updated with a new file (for instance, a higher quality version), does will rclone/rclone browser notice this change and replace the source folder with the new file?

**Comment by mmozeiko** [comment]
RcloneBrowser will do exactly same things as rclone. So your questions are really about rclone, not the GUI :)

Anyways, rclone offers different ways to compare files. By default it compares size and modification time. If those differ, then it will assume that source has different file and it will overwrite file in destination. But *beware* - some remotes doesn't support modification time. For example, ACD doesn't support modification time.

You can override this behavior with different arguments. You can make check only on size, or only on modification time, or only on checksum, or size and checksum. For example, if you want to compare size and checksum, then rclone will do very simple and fast check on size. If they are different, that means file must be transferred. If size is equal, then it will use checksum value for comparison. Some remotes support precalculated checksums (meaning they are calculated when file is uploaded, and there's no need to retrieve file when rclone asks for checksum). But there is again same limitation - some remotes doesn't support checksums at all. For example - crypt remote doesn't offer checksums.

So, as an example let's say you have files uploaded to encrypted ACD remote. This means  your only choice to compare files will be size difference. Because ACD doesn't support modification time and crypt doesn't support checksums. There have been some talk in rclone github issue to support these missing features - meaning if remote doesn't offer support to store custom modification time or checksum, then rclone could store that in some simple database in root of remote (or something similar). So this will improve with newer rclone releases.
