### ISSUE TITLE
Repeat a job

### ISSUE THREAD

**Issue by jarfil** [mmozeiko/RcloneBrowser#20]
After a job completes, I may want to execute it again to upload new files from the same source to the same target with the same options.

Allow repeating a job, or cloning a job, or creating a new job with the same parameters.

Additional related features might be:
* export & import a job
* schedule a job
* pause a job

**Comment by mmozeiko** [comment]
I really think that this sounds like a job for rclone.exe itself - just put arguments in .bat file and run it whenever you want it. I don't want to complicate GUI much (especially scheduling part), it should stay simple.

But I may be biased here, because I made RcloneBrowser for... well browsing. Uploading/Downloading is just an extra feature I quickly threw together at the end :)

Anyways I think adding an export of rclone.exe arguments for existing job to .bat/.sh file sounds like an useful feature.

Pausing may be tricky - I cannot between file uploads (because I don't have information when rclone finishes each file upload). But pausing in middle of file upload may not play well with some remotes - remote could decide transfer is timeout'ed and terminate connection or something like that.

**Comment by mmozeiko** [comment]
I've added copy to clipboard button for running or finished jobs.
