### ISSUE TITLE
Remote Access to Encrypted Files

### ISSUE THREAD

**Issue by polayer6** [mmozeiko/RcloneBrowser#67]
Very useful program you have developed.  I was wondering if there was any way to replicate some of the features in the mobile environment.  Specifically, I need access to encrypted files and I'm not always in front of the computer to use your program or have RCLONE download/decrypt for access.  Your program makes access to these files incredibly easy, with the cavet of having to work with a machine locally.  I know the backend depends on RCLONE to handle most of the tasks, but I was curious about the feasibility of having access to these encrypted folders at all times.   I'm not sure if this is possible, but it would be amazing to automate my tasks locally and have access to the encrypted files the moment I need them.

**Comment by 2600box** [comment]
i can run rclone on my andoird phone. arm32bit version

**Comment by polayer6** [comment]
Are you able to decrypt files on android?  I only need access to pdf's, spreadsheets, and word documents.  Nothing to intense, but having access these files on demand would be amazing.  I'm on IOS, so hopefully there is a solution for the mobile environment.

**Comment by mmozeiko** [comment]
This software is really written for desktop usage. Porting to Andorid or other mobile OS is technically possible, but usability will be terrible due to usage of desktop-like widgets. And maintenance will be annoying. Writing UI for mobile platform would better be done as separate project. It would be pretty trivial to support rclone encryption - its encrypted file format is super simple and is well documented: https://rclone.org/crypt/#file-formats

Basically if you want to open rclone encrypted files on Android it would be much easier just to write plugin to existing cloud storage applications. For example for Solid Explorer: http://neatbytes.com/solidexplorer/ It already provides multiple plugins for various functionality. Try contacting author and ask to support rclone encryption. They won't need to reimplement access to cloud storages (Google Drive, Dropbox, ...) because that app already has that. It only need to add support for rclone encryption file format.
